# Generated by Django 4.2.4 on 2023-08-29 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosmart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosmart.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosmart.register')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosmart.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosmart.register')),
            ],
        ),
    ]
