# Generated by Django 4.2.4 on 2023-09-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecosmart', '0005_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
