# Generated by Django 4.2.4 on 2023-09-02 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosmart', '0006_rename_amount_payment_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosmart.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosmart.register')),
                ('user_shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosmart.shippingaddress')),
            ],
        ),
    ]
